package gmark;

import org.apache.flink.api.java.ExecutionEnvironment;
/*
* Run this class to convert CSV files generated by gMark to a labeled property graph data model
* */

public class GMarkDataGenerator {
	public static void main (String[] args) throws Exception {
		ExecutionEnvironment env = ExecutionEnvironment.getExecutionEnvironment();
		//Specify the directory storing all CSV files, which could be determined either by input arguments or a absolute path in the main function
		String dir = args[0];
		//String dir = "C:/Users/s146508/Desktop/";
		GMarkToGraphDataModel gmarkGraph = new GMarkToGraphDataModel(dir, env);
		gmarkGraph.getGraph();
		
	}
}
