package ldbc;


import org.apache.flink.api.java.ExecutionEnvironment;

/*
* Run this class to convert CSV files generated by LDBC-SNB to a labeled property graph data model
* */
public class LDBCDataGenerator {
	public static void main(String[] args) throws Exception {
		final ExecutionEnvironment env = ExecutionEnvironment.getExecutionEnvironment();

		//Specify the directory storing all CSV files, which could be determined either by input arguments or a absolute path in the main function
		String dir = args[0];
		//String dir = "C:/path/path/";
		LDBCToGraphDataModel ldbcGraph = new LDBCToGraphDataModel(dir, env);
		ldbcGraph.getGraph();
	
	}
}
